version: 2

models:
  - name: stg_profile
    description: >
      Menyimpan informasi demografis penerima manfaat Medicare, termasuk jenis kelamin, tanggal lahir, tanggal meninggal, ras, dan ESRD.
    columns:
      - name: bene_id
        description: ID unik penerima manfaat.
      - name: gender
        description: Jenis kelamin (Male/Female).
      - name: birth_date
        description: Tanggal lahir.
      - name: death_date
        description: Tanggal kematian (jika ada).
      - name: race_code
        description: Kode ras.
      - name: esrd_indicator
        description: Indikator penyakit ginjal tahap akhir.

  - name: stg_coverage
    description: >
      Menyimpan informasi jumlah bulan cakupan HI, SMI, HMO, Rx, dan informasi kontrak plan.
    columns:
      - name: bene_id
        description: ID unik penerima manfaat.
      - name: hi_coverage_months
        description: Jumlah bulan cakupan Hospital Insurance.
      - name: smi_coverage_months
        description: Jumlah bulan cakupan Supplemental Medical Insurance.
      - name: hmo_coverage_months
        description: Jumlah bulan dalam HMO.
      - name: plan_coverage_months
        description: Jumlah bulan cakupan plan Medicare Advantage.
      - name: rx_coverage_months
        description: Jumlah bulan cakupan obat resep.
      - name: contract_id
        description: ID kontrak plan Medicare.
      - name: segment_id
        description: ID segmen plan.
      - name: pbp_id
        description: ID plan benefit package.

  - name: stg_location
    description: >
      Menyimpan informasi geografis seperti ZIP Code dan FIPS terakhir yang tercatat, serta state code.
    columns:
      - name: bene_id
        description: ID unik penerima manfaat.
      - name: zip_code
        description: ZIP Code terakhir yang tercatat.
      - name: state_county_fips
        description: Kode FIPS wilayah terakhir.
      - name: state_code
        description: Kode negara bagian penerima manfaat.

  - name: stg_status
    description: >
      Menyimpan status Medicare per bulan hasil unpivot dari kolom 01-12 dan dipartisi berdasarkan bulan.
    columns:
      - name: bene_id
        description: ID unik penerima manfaat.
      - name: status_code
        description: Kode status Medicare.
      - name: status_month
        description: Tanggal awal bulan status (dipakai untuk partisi).
